myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6app.urls')),
    path('', include('story9app.urls')),
]

story6app/urls.py
from django.urls import path
from . import views

app_name ="story6app"

urlpatterns = [
    path('', views.profile_page, name="profile"),
    path('landingpage/', views.landing_page, name="landingpage"),
    path('landingpage_add/', views.landing_page_add_status, name="landingpage_add"),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('validate/', views.validate),
    path('success/', views.success, name='success'),
]

story9app/urls.py
from django.urls import path
from . import views

app_name ="story9app"

urlpatterns = [
    path('wishlist/',views.story9_page,name='story9'),
    path('laptop/',views.laptop_page,name='laptop-page'),
]

story6app/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Activity(models.Model):
    message = models.CharField(max_length = 800)
    time = models.DateTimeField(auto_now_add=True)

class Subscriber(models.Model):
    name = models.CharField(max_length = 50)
    password = models.CharField(max_length = 20)
    email = models.CharField(max_length = 50)

story9app/models.py
from django.db import models

# Create your models here.
class WishlistLaptop(models.Model):
    name = models.CharField(max_length = 200)
    img = models.CharField(max_length = 200)
    desc = models.CharField(max_length = 200)
    price = models.CharField(max_length=200)

story6app/forms.py
from django import forms

class StatusForm(forms.Form):
	status_attrs = {
	    'type':'text',
	    'class':'form-control',
	    'placeholder':'Your Mood',
	}
	message = forms.CharField(max_length = 800, widget = forms.TextInput(attrs = status_attrs), label = "What's Your Mood?")

class SubscribeForm(forms.Form):
    email_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Example: email@gmail.com',
    }
    name_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Full Name',
    }
    pass_attrs = {
        'type': 'password',
        'class': 'form-control',
        'placeholder':'Password',
    }
    name = forms.CharField(max_length = 50, error_messages={"required": "Please enter your name"}, widget = forms.TextInput(attrs=name_attrs))
    password = forms.CharField(max_length = 20, min_length=6, widget = forms.PasswordInput(attrs=pass_attrs), error_messages={"min_length": "password must be longer than 5 characters"})
    email = forms.EmailField(error_messages={"required": "Please enter a valid email"}, max_length=50, widget=forms.TextInput(attrs=email_attrs))

story6app/views.py
from django.shortcuts import render, redirect
from .forms import StatusForm, SubscribeForm
from .models import Activity, Subscriber
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def landing_page_add_status(request):
    form = StatusForm(request.POST or None)
    response = {}
    if(request.method == 'POST' and form.is_valid()):
        response['message'] = request.POST['message']
        activity = Activity(message = response['message'])
        activity.save()
        return HttpResponseRedirect('/landingpage/')
    else:
        return HttpResponseRedirect('/landingpage/')

def landing_page(request):
    response = {}
    news = Activity.objects.all()
    form = StatusForm()
    return render(request, 'story6_landingpage.html', {'form': form, 'news': news})

def profile_page(request):
    response = {}
    return render(request, 'story6_profile.html', response)

def subscribe(request):
    response = {}
    response["forms"] = SubscribeForm()
    return render(request, 'story10_subscribe.html', response)
    
@csrf_exempt
def validate(request):
    email = request.POST.get("email")
    data = {'not_valid': Subscriber.objects.filter(email__iexact=email).exists()
    }
    return JsonResponse(data)

def success(request):
    submited_form = SubscribeForm(request.POST or None)
    if (submited_form.is_valid()):
        cd = submited_form.cleaned_data
        new_subscriber = Subscriber(name=cd['name'], password=cd['password'], email=cd['email'])
        new_subscriber.save()
        data = {'name': cd['name'], 'password': cd['password'], 'email': cd['email']}
    return JsonResponse(data)

story9app/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
import requests

# Create your views here.

def laptop_page(request):
    laptop_url = "https://enterkomputer.com/api/product/notebook.json"
    temp = requests.get(laptop_url).json()
    laptop_json = []
    for items in temp:
        if "Intel" in items['details']:
            laptop_json.append(items)
    laptop_list = []
    count = 0
    for i in range(200,400,1):
        pc_dict = {"id":laptop_json[i]["id"],
        "name":laptop_json[i]["name"],
        "details":laptop_json[i]["details"],
        "brand":laptop_json[i]["brand"], 
        "price":laptop_json[i]["price"]}
        laptop_list.append(pc_dict)
    return JsonResponse({'data':laptop_list})

def story9_page(request):
    response = {}
    return render(request, 'story9_page.html', response)

story6app/templates/story10_subscribe.html
{% extends 'base.html' %}
{% block content %}
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.min.css">

  {% load static %}
  <link href="{% static 'style_story6.css' %}" type="text/css" rel="stylesheet"/>
  <script src="{% static 'js_story10.js' %}"></script>

  <title>Subscribe to WebnyaMela</title>
  </head>

  <body>
    <div class ="container">
      <h1 class="text-center m-2"id="title">Subscribe to WebnyaMela</h1>
      <div class="row m-5">
          <div class="col-md-4"></div>
          <div class="col-md-4">
              <form method="POST">
                  <div class="form-group">
                      {%csrf_token%}
                      {{forms}}
                  </div>
                  <button id= "submit_subscribe" disabled= "disabled" type="submit" class = "btn btn-dark">Subscribe</button>  
              </form>
          </div>
          <div class="col-md-4"></div>
      </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.all.min.js"></script>
  {% endblock %}
</body>
</html>

story6app/templates/story6_landingpage.html
<!doctype html>
<html lang="en">
    
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% load static %}
    <link href="{% static 'style_story6.css' %}" type="text/css" rel="stylesheet"/>

    <title>Apa Kabar?</title>
</head>

<body>
    <div class="container-fluid judul-lp">
        <div class ="row">
            <div class ="col-sm-8" style="float: none; margin: 0 auto;">
                <h1>Hello! How Are You?</h1>
                <form action="{% url 'story6app:landingpage_add' %}" method="POST">
                        <div class="form-group">
                            {% csrf_token %}
                            {{ form }}
                        </div>
                        <button type="submit" class="btn btn-primary">Tell It!</button>
                </form>
            </div>      
        </div>
    </div>
    <div class="container-fluid lpnya">
        <div class="row">
            <div class ="col-sm-8" style="float: none; margin: 0 auto;">
                <div class="panel panel-default">
                    <br>
                    <div class="panel-body">
                        <table style="width:100%;" class="center">
                                {% if news %}
                                    {% for mood in news %}
                                    <tr>
                                        <td>{{ mood.message }}</td>
                                        <td>{{ mood.time }}</td>
                                    </tr>
                                    {% endfor %}
                                {% else %}
                                {% endif %}
                        </table>
                        <br><br>
                        <p>Thank You For Telling Me!</p>
                        <div class="link-profile" style="text-align: center">
                            <a href="/" class="btn btn-light" style="border-color: #AFCBFF; color: #3D348B; font-family: Karla; font-style: normal; font-weight: bold; font-size: 18px">
                                Go to My Profile</a>
                        </div><br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

story6app/templates/story6_profile.html
{% extends 'base.html' %}
{% block content %}
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% load static %}
  <link href="{% static 'style_story6.css' %}" type="text/css" rel="stylesheet"/>
  <script src="{% static 'js_story8.js' %}"></script>

  <title>Khameela's Profile</title>
  </head>

  <body>
    <div id="loader">
      <div class="spinner"></div>
    </div>      
    <br><br>
  	<div class = "container webnya">
      <div class="row">
        <div class="col-sm-4 image overlay">
          <img class="profile" src="http://mela-ppw.herokuapp.com/foto.png">
          <div class="judul">Khameela Rahmah.</div>
          <div class="little-desc">
            <ul style="list-style-type:none;">
              <li>NPM: 1706023422</li>
              <li>19 yo.</li>
              <li>Student.</li>
              <li>Scorpion.</li>
              <li>INFP.</li>
            </ul> 
          </div>
        </div>
        <div class="col-sm-8 teks-deskripsi">
          <div class="row">
          <div class="col-sm">
            <br>
            <div class="judul-desc">A little more about myself</div>
            <div class="desc">Her friends and family called her Mela. Was born in Jakarta on October 26, 1999. The 2nd child in the family. Currently studying at Fasilkom Universitas Indonesia. Like Japanese Vibes and wish someday could go there. Like listening to good musics and watch good movies.</div>
            <br>
            <div class="judul-desc">Educations</div>
            <div class="desc">
              <dl>
                <dt>Universitas Indonesia</dt>
                <dt>SMAN 39 Jakarta</dt>
                <dt>SMPN 49 Jakarta</dt>
                <dt>SDN Dukuh 09 Pagi</dt>
              </dl> 
            </div>
          </div>
          <div class="col-sm-12">
            <button class="accordion">Activities</button>
            <div class="panel panel-profile">
              <br>
              <p>Desain Poster</p>
              <p>Mengerjakan Tugas</p>
            </div>
            <button class="accordion">Organizations</button>
            <div class="panel panel-profile">
              <br>
              <p>Biro Media BEM Fasilkom UI</p>
              <p>Divisi Dekorasi CGT 2018</p>
              <p>Divisi Press COMPFEST X</p>
              <p>Divisi HPK PMB 2018</p>
              <p>Divisi Kreatif Wisgan 2019 </p>
            </div>
            <button class="accordion">Achievements</button>
            <div class="panel panel-profile">
              <br>
              <p>Tepat Waktu</p>
              <p>Bangun Pagi</p>
            </div>
            <br>
          </div>
          <div class="col-sm-11 col-centered">
            <button id = "daymode" class="btn btn-light" style="background-color: #AFCBFF; color: #13274A; font-family: Karla; font-style: normal; font-weight: bold; font-size: 18px">Day Mode</button>
            <button id = "nightmode" class="btn btn-dark" style="background-color: #13274A; color: #AFCBFF; font-family: Karla; font-style: normal; font-weight: bold; font-size: 18px">Night Mode</button>
            <br>
          </div>
          </div><br>
      </div>
  </div>
</div><br><br>
{% endblock %}
</body>
</html>

story9app/templates/story9_page.html
<!doctype html>
<html lang="en">
<head>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% load static %}
  <script src="{% static 'js_story9.js' %}"></script>
  <!-- Materialize -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <!-- NumeraliaJS for formatting currency -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.4.0.js" integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo="crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <style>
  body {
      background-color: #AFCBFF;
  }
  .judul {
      color: #13274A; 
      font-family: Karla; 
      text-align: center;
      font-style: normal; 
      font-weight: bold; 
      font-size: 30px
  }
  h5{
      font-family: Karla;
      color: #3D348B;
      font-style: normal;
      font-weight: bold;
      text-align: center;
  }
  </style>
  <title>My Wishlist</title>
</head>

<body onload="getlaptop(0)">
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <div class="judul">My Wishlist</div>
    </div>
    </div>
    <div class = table-responsive>
      <table id="tablenya" style="width:100%"></table>
    </div>
    <div class="row">
      <div class="col">
        <h5>Total Harga Wishlist</h5>
        <div class="judul">
            <span>Rp. </span><span id="tobuy">0</span>
        </div>
      </div>
    </div>
  </div>
  <center>
      <div id="paginated"></div>
  </center>
</body>
</html>

templates/base.html
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
 

  </head>

  <body>
      {% include "story3_navbar.html" %}

      {% block content %}
      {% endblock %}
</body>
</html>

templates/story3_navbar.html
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <link href="https://fonts.googleapis.com/css?family=Rubik:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  <style>
  .navbar {
    background: #0E1C36;
  }
  
  .navbar-nav {
    font-family: Rubik;
    font-style: normal;
    font-weight: bold;
    line-height: normal;
    font-size: 15px;
  }
  </style>

  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" style="border-color: #FFEDE1">
        <span class="navbar-toggler-icon"></span>
      </button> 
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/" style="color: #FFEDE1">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/subscribe/"style="color: #FFEDE1">Subscribe</a>
              </li>
          </ul>
        </div>  
      </nav>
</body>
</html>